version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis_datas:/data

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'

volumes:
    redis_datas:
